### ISSUE TITLE
International flights not working? 

### ISSUE THREAD

**Issue by mjrichmo** [aortbals/southwest-checkin#35]
Hey Aaron, thanks so much for creating this site. It's a pretty freaking sick piece of code. 

I'm running into an error with one of my interaries: 7H3LJK 
it doesn't show the normal flight info and when it will check-in. I'm thinking its a problem with the checkin system for international travel which hasn't started yet. Just thought I'd give u a heads up. Again, amazing work!

note: one is for cancun, one for punta cana, new routes on southwest. it lets me checkin--but gives an error. then when never notifies me or shows the checkin time. ideas? 

SICK CODE.

**Comment by aortbals** [comment]
Version 2.0 is now [released](https://chkmein.co). I believe this should now work. Please file a new issue for any problems that arise.

**Comment by aortbals** [comment]
A further note on this issue: because of current limitations on international checkins, international flights are not supported. This is unfortunate, but it's a known limitation at this point. I will add support if I can in the future.

**Comment by mjrichmo** [comment]
Hey Aaron! Did the site go down? Really loved the tool and it was really
well done!

**Comment by mjrichmo** [comment]
Still working on your end?

**Comment by mjrichmo** [comment]
If u send me the code and instructions I'll rehost it and send you a link so you don't have to store it remotely

**Comment by kczauz** [comment]
last time i tried to checkin, this didnt work.  It accepted all my inputs
and said i had a pending checkin, but the checkin was never completed.  I
tried this about a month ago, haven't had any flights since then.

**Comment by mjrichmo** [comment]
It was so over powered..saved so much from a list
