### ISSUE TITLE
Automatic check-in failed

### ISSUE THREAD

**Issue by pqrs6** [aortbals/southwest-checkin#36]
I used this successfully in August, but for a flight in November on the same route the web app failed silently. The online app suggests that the checkin is pending (confirmation code is FGBB3H) and I got no e-mail for either the departing or returning trip. I suspect the southwest checkin website has changed slightly in the meantime?

As far as I can tell, I did the same actions as whe this worked correctly (FM7GM2).

**Comment by aortbals** [comment]
@pqrs6 see https://github.com/aortbals/southwest-checkin/issues/38#issuecomment-69204736

**Comment by aortbals** [comment]
Version 2.0 is now [released](https://chkmein.co). Please file a new issue for any problems that arise.
