### ISSUE TITLE
Auto check-in for return flight failed.

### ISSUE THREAD

**Issue by joshkim** [aortbals/southwest-checkin#37]
Not sure if it's associated with previous issue: https://github.com/aortbals/southwest-checkin/issues/36

The departure flight worked, but the flight back wasn't checked in correctly.

**Comment by evliu** [comment]
I only book one-way flights now and it failed for my dec 19th checkin. maybe the site did change

**Comment by evliu** [comment]
The checkin worked for me today so maybe it was just temporarily down.

**Comment by aortbals** [comment]
@joshkim, @evliu,  please see https://github.com/aortbals/southwest-checkin/issues/38#issuecomment-69204736

**Comment by aortbals** [comment]
Version 2.0 is now [released](https://chkmein.co). This should be fixed. Please file a new issue for any problems that arise.
