### ISSUE TITLE
Check in failed on one of two conf #'s for the same flight

### ISSUE THREAD

**Issue by flamtapgt** [aortbals/southwest-checkin#38]
I tried this for a flight I'm going to cancel anyways. I had two different conf #'s to check in for the same flight. One of them was checked in and I got the confirmation email, but the other one was apparently not checked in. I did not get the confirmation email and the site still showed as pending. 

I can provide the confirmation numbers involved if needed.

**Comment by aquanymous** [comment]
This failed silently this morning for my daughter and for me (separate reservations and check in requests)  As with the OP, when I went to the site, it still showed the check in as pending, even though the check in window had opened 90 minutes previously.  This program did work for us on a Dec 15th check in though.  I can provide confirmation numbers and the emails generated by the heroku web interface if needed, both for the check ins that worked and the ones that didn't.

**Comment by josecomboni** [comment]
I created a system for autocheckins inspired on this project and jbeda's original script. You can check it out here https://github.com/springyleap/southwest-autocheckin.

**Comment by flamtapgt** [comment]
@josecomboni Thanks. I just tested it with 2 conf #'s successfully. 

flamtap

**Comment by aortbals** [comment]
@flamtapgt, @aquanymous, I'm working on a ground up rewrite of this service that will eliminate a lot of the unreliability that users are experiencing when southwest's site changes. Stay tuned for this to land, which will fix these various check in issues. It will also support features like user accounts, etc, which will make using the service much easier.

Cheers,
Aaron

**Comment by aortbals** [comment]
Also, I will also provide a migration path so that users with currently scheduled check ins will not get lost. They will be migrated over to the new check in system.

**Comment by aquanymous** [comment]
This sounds great!  Looking forward to giving it a try when it goes live.

**Comment by aquanymous** [comment]
@josecomboni , thanks!  Just registered two flights for next week.  They are two separate confirmation numbers for the same one way itinerary, but both registered with the same email.  The passenger names are, of course different, but wanted to double check that the shared email won't cause an error.

**Comment by swa-user** [comment]
Thanks!

**Comment by aquanymous** [comment]
@josecomboni. Your auto check in springyleap worked great for us 3 days ago.   One was five better than the other for the first flight, and two better on the second.  Does it submit all check in requests simultaneously for a given flight, or based on the time they were registered through springyleap?  Just curious.  Both boarding positions were fine and it's great to have an automatic check in option.  Thanks so much!

**Comment by josecomboni** [comment]
@aquanymous let's take this conversation to the project's site (I'm opening a new issue to reply to your questions - https://github.com/springyleap/southwest-autocheckin/issues/1), thanks.

**Comment by zackshapiro** [comment]
@aortbals Any ETA on the rewrite? I know you just commented a month ago, just curious about how close you are to releasing. Love the tool

**Comment by aortbals** [comment]
@zackshapiro its pretty far along. The majority is done. I'd like to release it between now and early march.

**Comment by noiz** [comment]
@aortbals Will the new rewrite support multiple travelers on the same confirmation number to check both in?

**Comment by aortbals** [comment]
@noiz yes it will.

**Comment by Braunson** [comment]
Any updates on the release? Does the current demo still work? I'm looking tomorrow to checkin for 6am..

**Comment by aortbals** [comment]
Version 2.0 is now [released](https://chkmein.co). Please file a new issue for any problems that arise.

**Comment by jctull** [comment]
The site looks great! I have a flight on Monday, so we will see how things perform soon. Thanks, as always, for your efforts!

John

**Comment by zackshapiro** [comment]
Nice work on this! Using on my flight Tuesday

Thanks Aaron

Best,
Zack

**Comment by aortbals** [comment]
Glad it is useful :).
