### ISSUE TITLE
Is http://southwest-checkin.herokuapp.com/ working?

### ISSUE THREAD

**Issue by ozziemlee** [aortbals/southwest-checkin#39]
Hi there, I've been trying to check in for a flight a month ago and I keep getting the message that "We can't find that reservation!".  I've entered the Confirmation Number, First Name, Last Name, and the email address used per my receipt.  I successfully used the site back in November...

Please let me know if you require more information.  Thanks!

**Comment by josecomboni** [comment]
@ozziemlee I have a similar service to help you with your southwest flights checkin needs. You can check the project's page in github at https://github.com/springyleap/southwest-autocheckin

**Comment by aortbals** [comment]
Version 2.0 is now [released](https://chkmein.co). This should be fixed. Please file a new issue for any problems that arise.
