### ISSUE TITLE
Can App handle multiple people on one confirmation #?

### ISSUE THREAD

**Issue by Austin1** [aortbals/southwest-checkin#40]
I have 6 people flying on the same confirmation number. When I check in each person, it seems to just keep the very first person that I checked in and ignore future submissions using that same confirmation number.

**Comment by josecomboni** [comment]
Hi Austin1,

I have a similar service to help you with your southwest flights checkin needs. You can check the project's page in github at https://github.com/springyleap/southwest-autocheckin

**Comment by aortbals** [comment]
Version 2.0 is now [released](https://chkmein.co). This should be fixed.
