### ISSUE TITLE
Migration to new API

### ISSUE THREAD

**Issue by aortbals** [aortbals/southwest-checkin#46]
Recently (~ March 2016), Southwest released a new API and deprecated and disabled the old API. If you've seen this message:

> We retired this version to the hangar. Visit the app store and update to the latest version. The app requires iOS 8.0 or later.

This means you've seen this issue. This issue will track the implementation of the new API. The API is completely different, so the api client needs some significant changes and is being worked on.

**Comment by d3fc0n** [comment]
I appears the old API is still being used by Android app.  I made minor changes to request.rb, everything seems to be working properly.

> d3fc0n@remotehost:/opt/southwest-checkin$ sdiff  -s changes.txt lib/southwest/request.rb
        platform: 'iPhone',                                   |         platform: 'android',
      "Southwest/#{app_version} CFNetwork/711.1.16 Darwin/14. |       "Apache-HttpClient/android/A0001"
      "2.10.1"                                                |       "2.22.0"
