### ISSUE TITLE
CheckinParser Error

### ISSUE THREAD

**Issue by francirp** [aortbals/southwest-checkin#49]
The following error occurs for reservations containing multiple passengers:

```undefined local variable or method `doc' for #<CheckinParser:0x007f5b31c3daa0>```

I believe we need to use  ```passenger_checkin_document``` instead of ```doc``` in the below code snippet taken from app/parsers/checkin_parser.rb. I would submit the PR but my fork has a bunch of commits you're not going to want pulled into master @aortbals.

```ruby
  def passenger(passenger_checkin_document)
    passengers = checkin_record.reservation.passengers
    if passengers.count == 1
      passengers.first
    else
      passengers.where(
        first_name: doc['passenger']['secureFlightFirstName'],
        last_name: doc['passenger']['secureFlightLastName']).first
    end
  end
```

**Comment by aortbals** [comment]
Thanks for reporting @francirp - do you have a test flight you can send me privately so I can reproduce and create a test case for it?

**Comment by francirp** [comment]
Sorry for dropping the ball on this @aortbals but glad to see you got it fixed
