### ISSUE TITLE
Did southwest close down the API that this app uses?

### ISSUE THREAD

**Issue by wootwoot1234** [aortbals/southwest-checkin#51]
I'm getting an error when I try to enter a reservation.

> There was a problem retrieving your reservation. Please check the following fields to make sure they are correct:

> We retired this version to the hangar. Visit the app store and update to the latest version. The app requires iOS 8.0 or later.

**Comment by joshk6656** [comment]
Don't use the zip file in the release tab. Use the zip from the current branch

**Comment by wootwoot1234** [comment]
Thanks!

**Comment by coreywhiting** [comment]
I'm receiving the same error off of the latest code in the master branch. Any thoughts? Did the API change?
