### ISSUE TITLE
How do I configure email?

### ISSUE THREAD

**Issue by wootwoot1234** [aortbals/southwest-checkin#54]
I'm running this on Heroku but don't have email configured.  Are there any instructions on how to setup email support?

**Comment by wootwoot1234** [comment]
I figured it out and added the instructions for Heroku to the readme in this PR https://github.com/aortbals/southwest-checkin/pull/53

**Comment by herocertified** [comment]
I followed the instructions in your pull request but can't get emails to send still.

Any tips?
