### ISSUE TITLE
ActiveRecord::RecordInvalid: Validation failed: Flight can't be blank

### ISSUE THREAD

**Issue by flyize** [aortbals/southwest-checkin#56]
Let me preface this with the fact that I'm a Ruby Rookie.  I've probably done something dumb...

I'm slowly walking through the README and getting things setup.  When running 

rake dev:prime

I get the following error
`rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Flight can't be blank
/home/ec2-user/.gem/ruby/2.2/gems/activerecord-4.2.0/lib/active_record/validations.rb:79:in `raise_record_invalid'
/home/ec2-user/.gem/ruby/2.2/gems/activerecord-4.2.0/lib/active_record/validations.rb:43:in `save!'
/home/ec2-user/.gem/ruby/2.2/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/ec2-user/.gem/ruby/2.2/gems/activerecord-4.2.0/lib/active_record/transactions.rb:291:in `block in save!'
/home/ec2-user/.gem/ruby/2.2/gems/activerecord-4.2.0/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
/home/ec2-user/.gem/ruby/2.2/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/ec2-user/.gem/ruby/2.2/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/home/ec2-user/.gem/ruby/2.2/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/ec2-user/.gem/ruby/2.2/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/home/ec2-user/.gem/ruby/2.2/gems/activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
/home/ec2-user/.gem/ruby/2.2/gems/activerecord-4.2.0/lib/active_record/transactions.rb:291:in `save!'
/home/ec2-user/.gem/ruby/2.2/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/active_record_helper.rb:34:in `block in save!'
/home/ec2-user/.gem/ruby/2.2/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent.rb:574:in `with_database_metric_name'
/home/ec2-user/.gem/ruby/2.2/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/active_record_helper.rb:33:in `save!'
/home/ec2-user/sw/lib/tasks/dev.rake:31:in `checkin_flight'
/home/ec2-user/sw/lib/tasks/dev.rake:22:in `block in checkin_reservation'
/home/ec2-user/.gem/ruby/2.2/gems/vcr-2.9.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call'
/home/ec2-user/.gem/ruby/2.2/gems/vcr-2.9.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
/home/ec2-user/.gem/ruby/2.2/gems/vcr-2.9.3/lib/vcr.rb:182:in `use_cassette'
/home/ec2-user/sw/lib/tasks/dev.rake:20:in `checkin_reservation'
/home/ec2-user/sw/lib/tasks/dev.rake:49:in `block (2 levels) in <top (required)>'
Tasks: TOP => dev:prime
(See full trace by running task with --trace)
`

What am I missing?  Thanks for any help.

**Comment by flyize** [comment]
Okay, I was able to use the Heroku walk through to get this installed.  

Can someone hopefully explain to me how to administrate this?

**Comment by flyize** [comment]
So I went back to Amazon Linux because I just like it better than Heroku.  Anyway, how can I deal wthi this error:

[ec2-user@ip-172-16-2-91 southwest-checkin]$ rake dev:prime
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Flight can't be blank
/home/ec2-user/southwest-checkin/lib/tasks/dev.rake:31:in `checkin_flight'
/home/ec2-user/southwest-checkin/lib/tasks/dev.rake:22:in `block in checkin_reservation'
/home/ec2-user/southwest-checkin/lib/tasks/dev.rake:20:in `checkin_reservation'
/home/ec2-user/southwest-checkin/lib/tasks/dev.rake:49:in `block (2 levels) in <top (required)>'
Tasks: TOP => dev:prime
(See full trace by running task with --trace)

**Comment by rsulliv1** [comment]
any luck getting past that error? I saw the same, but just skipped the seeded data load. I had a reservation that seemed to check in (ui shows it as checked in & I received an email from the system).

doesn't look like my return res checked in at all though. i'm wondering if i'm having an issue with redis since I have the standalone version and another version installed via yum. I don't remember which one I had running when it initially worked.. but, I see that someone else has a similar issue with their return trip, so maybe it's that bug...

**Comment by flyize** [comment]
I have not gotten it work yet...

**Comment by virento** [comment]
I'm experiencing this issue as well.
