### ISSUE TITLE
Error on adding new reservation

### ISSUE THREAD

**Issue by coreywhiting** [aortbals/southwest-checkin#59]
I'm receiving an error while trying to add a new reservation.

> We retired this version to the hangar. Visit the app store and update to the latest version. The app requires iOS 8.0 or later.

I'm wondering if Southwest made a change to their API?

**Comment by joshk6656** [comment]
Did you use the zip from the release tab of github, or the latest source on the site?

You should be using this:
https://github.com/aortbals/southwest-checkin/archive/master.zip

Not this!
https://github.com/aortbals/southwest-checkin/archive/2.0.zip
