### ISSUE TITLE
No Issue - Great job! 

### ISSUE THREAD

**Issue by thePr0fessor** [aortbals/southwest-checkin#63]
Sorry - Had to just drop a note - awesome job guys!  You can delete this if you wish but I wanted to tell you you've got a great app here and if I (not a ruby guy but technical in nature (java, JS, PHP, Python, general sys admin badassery)) can be of any help with bug fixes or testing something I'm happy to do so. 

Thanks again!

**Comment by aortbals** [comment]
Thanks!
