### ISSUE TITLE
Multiple Passengers

### ISSUE THREAD

**Issue by francirp** [aortbals/southwest-checkin#67]
Right now only the first passenger is checked in. I'm not seeing any 500 errors come through, so I'm not sure why it's not working. I thought I'd post the issue to make you aware of it @aortbals and see if you have any clue as to what could be happening?

**Comment by aortbals** [comment]
Thanks for the report. This was closed via https://github.com/aortbals/southwest-checkin/pull/72

**Comment by francirp** [comment]
Beautiful. Thank you @aortbals!! 💯 👏
